export const categoris=[
    {
        id:1,
        name:'Weapons',
        thumbnail:require('../assets/Wepons.png'),
        description:'weapons',
    },
    {
        id:2,
        name:'Armors',
        description:'armors',
        thumbnail:require('../assets/Armors.png')
    },
    {
        id:3,
        name:'AoW',
        description:'ashes',
        thumbnail:require('../assets/AoW.png')
    },
    {
        id:4,
        name:'Incantations',
        description:'incantations',
        thumbnail:require('../assets/Inc.png')
    },
    {
        id:5,
        name:'Items',
        description:'items',
        thumbnail:require('../assets/Item.png')
    },
    {
        id:6,
        name:'NPCs',
        description:'npcs',
        thumbnail:require('../assets/NPC.jpg')
    },
    {
        id:7,
        name:'Shields',
        description:'shields',
        thumbnail:require('../assets/Shields.png')
    },
    {
        id:8,
        name:'Bosses',
        description:'bosses',
        thumbnail:require('../assets/Bosses.png')
    },
    {
        id:9,
        name:'Sorceries',
        description:'sorceries',
        thumbnail:require('../assets/Sorc.png')
    },
    {
        id:10,
        name:'Spirits',
        description:'spirits',
        thumbnail:require('../assets/Spirits.png')
    },
    {
        id:11,
        name:'Talismans',
        description:'talismans',
        thumbnail:require('../assets/Talisman.png')
    },

]